# Generated by Django 5.0.4 on 2024-04-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webportfolioapp', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
